apiVersion: v1
kind: Service
metadata:
  name: bottlesvc
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    service: bottle
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: bottle
  labels:
    name: bottle
spec:
  containers:
    - resources:
      image: lucidlabs/streams
      name: bottle
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP