apiVersion: v1
kind: Service
metadata:
  name: lucid-bottle
  namespace: default
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    service: lucid-bottle
  type: LoadBalancer

apiVersion: v1
kind: Pod
metadata:
  name: lucid-bottle
  labels:
    name: lucid-bottle
spec:
  containers:
    - resources:
      image: lucidlabs/streams
      name: lucid-bottle
      ports:
        - containerPort: 8081
          hostPort: 8081
          protocol: TCP